[package]
name = "paulzyw02/zt-birthday-app"
version = "0.1.4"
description = "Ziteng's 20th Birthday dynamic commemorative application ready for Wasmer Edge deployment"
license = "MIT"


[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
public = "dist"

[[command]]
name = "script"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
# This tells Wasmer to serve the 'dist' folder and fallback to index.html for React Router
env = [
  "SERVER_PORT=8080", 
  "SERVER_ROOT=/public", 
  "SERVER_PAGE_FALLBACK=/public/index.html",
  "SERVER_FALLBACK_PAGE_DOCUMENT=/public/index.html",
  "SERVER_ERROR_PAGE_404=/public/index.html"
]
