[package]
name = "paulzyw02/zt-birthday-app"
version = "0.1.1"
description = "Ziteng's 20th Birthday dynamic commemorative application ready for Wasmer Edge deployment"
license = "MIT"


[dependencies]
"wasmer/static-web-server" = "^1"

[[command]]
name = "web"
module = "wasmer/static-web-server:static-web-server"

[fs]
"/public" = "dist"
